### PR TITLE
ocpviz v0.2

### PR DESCRIPTION
**Pull request by alexbaden**
### Bug Fixes
 * x, y, and z bounds checking updated to match new OCP schema 

### New Features
 * Add data layer to current view
 * basic implementation of RAMON metadata support
 * full timeseries support with interactive controls
 * support for displaying project info from OCP for the primary token 

#### Note: 
This version requires ```python manage.py migrate``` and ```python manage.py collectstatic``` to function properly. 

## Additions to OCP Codebase
Wrote a json interface for ramon metadata. Implemented as ```jsonann.py``` in ocpca. Further implementation in ocpca (closely follows h5ann). All tests pass for both CAJAL and OCP.

### CODE REVIEW

**Comment by kunallillaney** [comment]
Look at #158.

**Comment by alexbaden** [comment]
I will handle those issues -- but I don't know how to add to the Sphinx
docs or write pytests. It will probably take some time for me to figure
that out, likely after SfN. I'd like to have this merged before SfN so all
the NUCs can run the same stack and so that everything demoed is available
on the main OCP site.

I ran the pytests and they all passed.

**Comment by kunallillaney** [comment]
Adding to pytests or sphinx is not hard. I can tell you how to do that. But this sort of a requirement from now on(uAlex had to do it as well). Simply because a lot of stuff is happening on the back-end and there is no sane way for me to deal with that. I would like it that they are done before I push them to master.

**Comment by alexbaden** [comment]
Test added. @kunallillaney can you merge this, now?

**Comment by alexbaden** [comment]
Thank you!!!!! :-)


Alex

**Pull request merged**
